// Package frontmatter provides YAML frontmatter parsing and generation for
// Markdown documents. Documents follow the convention:
//
//	---
//	<YAML block>
//	---
//	<body>
//
// The YAML block is delimited by lines containing only "---". The body is
// everything after the second delimiter.
package frontmatter

import (
	"bytes"
	"errors"
	"fmt"

	"github.com/goccy/go-yaml"
)

// ErrNoFrontmatter is returned when the input does not contain valid frontmatter
// delimiters. Callers may use errors.Is to distinguish this sentinel from other
// errors (e.g. malformed YAML inside a valid delimiter pair).
var ErrNoFrontmatter = errors.New("frontmatter: document does not contain --- delimiters")

// delimiter is the YAML frontmatter delimiter line.
var delimiter = []byte("---")

// Split separates the YAML frontmatter from the body of a document.
// The document must start with a line containing only "---" followed by the
// YAML content, another "---" line, and then the body.
//
// Returns (yamlPart, body, nil) on success, or (nil, nil, ErrNoFrontmatter)
// if the delimiters are missing, or (nil, nil, err) for a malformed structure.
//
// Body normalization: if the body has content but no trailing newline, Split
// appends one so callers can rely on a consistent byte representation.
func Split(data []byte) (yamlPart, body []byte, err error) {
	// Normalize line endings.
	data = bytes.ReplaceAll(data, []byte("\r\n"), []byte("\n"))

	lines := bytes.Split(data, []byte("\n"))

	// First line must be "---".
	if len(lines) == 0 || !bytes.Equal(bytes.TrimSpace(lines[0]), delimiter) {
		return nil, nil, ErrNoFrontmatter
	}

	// Find the closing "---" starting from line 1.
	closingIdx := -1
	for i := 1; i < len(lines); i++ {
		if bytes.Equal(bytes.TrimSpace(lines[i]), delimiter) {
			closingIdx = i
			break
		}
	}
	if closingIdx == -1 {
		return nil, nil, fmt.Errorf("frontmatter: unclosed delimiter (opening --- found but no closing ---): %w", ErrNoFrontmatter)
	}

	// yamlPart is everything between the two delimiters.
	yamlPart = bytes.Join(lines[1:closingIdx], []byte("\n"))
	if len(yamlPart) > 0 {
		yamlPart = append(yamlPart, '\n')
	}

	// body is everything after the closing delimiter.
	bodyLines := lines[closingIdx+1:]
	body = bytes.Join(bodyLines, []byte("\n"))
	// Preserve trailing newline: Join doesn't add a trailing newline, but the
	// original data likely had one. We re-add it only if there is body content.
	if len(body) > 0 && body[len(body)-1] != '\n' {
		body = append(body, '\n')
	}

	return yamlPart, body, nil
}

// Unmarshal parses YAML data into v (which must be a pointer).
// Uses github.com/goccy/go-yaml for field-order-preserving deserialization.
//
// For struct targets, fields are matched by yaml struct tags. For map targets,
// all keys are preserved in the order they appear in the YAML source.
func Unmarshal(data []byte, v any) error {
	return yaml.Unmarshal(data, v)
}

// Marshal serializes meta as YAML and concatenates body, producing a
// complete frontmatter document:
//
//	---
//	<marshaled meta>
//	---
//	<body>
//
// The YAML block is generated by goccy/go-yaml, which preserves struct field
// order as declared by yaml tags. For map[string]any meta, key order is
// implementation-defined by the library.
//
// Returns an error if meta cannot be marshaled to YAML.
func Marshal(meta any, body []byte) ([]byte, error) {
	return marshalWith(meta, body, yaml.Marshal)
}

// marshalWith is the injectable version of Marshal for testing.
// It accepts a custom marshaler function so tests can inject failures or
// custom output without depending on goccy/go-yaml internals.
func marshalWith(meta any, body []byte, marshaler func(any) ([]byte, error)) ([]byte, error) {
	yamlBytes, err := marshaler(meta)
	if err != nil {
		return nil, fmt.Errorf("frontmatter: marshal YAML: %w", err)
	}

	var buf bytes.Buffer
	buf.WriteString("---\n")
	buf.Write(yamlBytes)
	// Ensure the YAML block ends with a newline before the closing delimiter.
	// Note: goccy/go-yaml always appends a trailing newline, but we guard
	// defensively in case the marshaler parameter behaves differently.
	if len(yamlBytes) > 0 && yamlBytes[len(yamlBytes)-1] != '\n' {
		buf.WriteByte('\n')
	}
	buf.WriteString("---\n")
	buf.Write(body)
	return buf.Bytes(), nil
}
